version: '3'
services:
  nginx:
    container_name: sessak-nginx
    # build:
    #   context: ./nginx
    #   dockerfile: Dockerfile
    image: dozzzini/nginx:1
    volumes:
      #- ./nginx:/etc/nginx/conf.d
      # - ./staticfiles:/data/static
      - ./build:/usr/share/nginx/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  backend:
    container_name: sessak_backend
    # build:
    #   context: ./sessak_back
    #   dockerfile: Dockerfile
    image: dozzzini/back:1

    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/app/staticfiles

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
    - ./data/certbot/conf:/etc/letsencrypt
    - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dozzzini@naver.com --agree-tos --no-eff-email -d sessak.store

    depends_on:
      - backend
      - nginx
