version: '3'
services:
  nginx:
    container_name: sessak-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/data/static
    ports:
      - "80:80"
  backend:
    container_name: sessak_backend
    build:
      context: ./sessak_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./sessak_back/.env
    volumes:
      - ./staticfiles:/app/staticfiles