version: '3'
services:
  nginx:
    container_name: sessak-nginx
    # build:
    #   context: ./nginx
    #   dockerfile: Dockerfile
    image: dozzzini/nginx:1
    volumes:
      #- ./nginx:/etc/nginx/conf.d
      - ./staticfiles:/data/static
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    container_name: sessak_backend
    # build:
    #   context: ./sessak_back
    #   dockerfile: Dockerfile
    image: dozzzini/back:1

    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/app/staticfiles