# Generated by Django 4.2.5 on 2023-10-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='게시글 제목')),
                ('content', models.TextField(verbose_name='게시글 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='첨부파일')),
                ('view_num', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='게시글 작성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='게시글 수정날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='게시글 작성자')),
                ('category', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='categories.category', verbose_name='카테고리')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL, verbose_name='좋아요 누른 사람')),
            ],
        ),
    ]
