# Generated by Django 4.2.5 on 2023-10-09 10:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default=users.models.generate_random_string, max_length=5, unique=True),
        ),
    ]
